### ISSUE TITLE
Add configuration option to disable auto-start

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#170]
We enabled auto-start in v0.4.5, but to keep @Mpdreamz happy, we need a way to disable this :)

**Comment by Mpdreamz** [comment]
Some anecdotal back story why I think this is important

Back in december 2013 I spiked a real world application for 3 weeks in a team of two trying to develop a .NET website completely on our macs. Both of us were fullstack developers but the other guy being more a ruby dev took on the frontender role so he spent most of his time doing frontendy stuff. 

In such a setting the frontender is not completely isolated from c# (razor, small nancyfx module/mvc controller stuff) but doesn't always need the noise or added *weight* of omnisharp. Emphasising weight here because even if there is none, perceived weight plays a role too.

In the case of that project we already had a watcher in place to recompile on the fly and alert on the console when something was wrong and for the frontend dev this was enough or he was deliberately remodelling the razor views and in those cases it'd be nice to turn the whole machine off, do your shit, and turn it back on.
