### ISSUE TITLE
omnisharp-atom only works when the c# solution is the first in the project tree 

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#171]
When you have multiple trees open in the left hand bar, and the c# solution isn't the first, nothing works.

**Comment by david-driscoll** [comment]
There is a ton more work to do.  Basically we have a singleton server.  With multiple folders open we now need to be able to support more than one client per editor instance.  Already working on this with the node-client pr ( #157 ).


Basically I've removed `omni-sharp-server.ts` and `omni.ts` is now a facade for the `client-manager.ts`. 

`ClientManager` will give us an appropriate client for the project that a given editor is in (the active editor, or if you want a client for a specific editor you can do that too).

It will take some work because the status icon is bound directly to the current `singleton` use case.  

* My thought was if we could move the icon and integrate it into the treeview in someway that would work.
* We would also need to change around how the output window works because that could cause issues as well.  Two or more servers spamming the same output = :bomb:.  This could be another ticket though.
* We also have to consider the use case of global.json references.  If I'm hacking on my app and I have the MVC sources added through global.json, that extra `project` in atom could actually be using the same client as the first project.

**Comment by nosami** [comment]
Hmmm... I wasn't even thinking about multiple c# solutions, but I guess that is an issue too.

My problem was having a TS project tree come before the c# tree.

**Comment by david-driscoll** [comment]
That's what the client per folder is for.

I think part of the work should go into the client, to let it search to see if the path contains a valid project (or if it's hierarchy does).  So that we're not creating extra clients for projects that are not C# solutions.

**Comment by nosami** [comment]
Fixed by https://github.com/OmniSharp/omnisharp-atom/pull/322
