### ISSUE TITLE
Add solution wide code check

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#177]
This is possible by using the /codecheck endpoint without a file name. It would be great to see all errors without having to build.

**Comment by nosami** [comment]
So.. What should we do about this? Bring back the error pane, or wait for linter to support multiple files?

**Comment by david-driscoll** [comment]
lets not bring back the error pane, but lets bring in a nice error pane.

Maybe https://github.com/tcarlsen/atom-message-panel would help?

**Comment by nosami** [comment]
:+1: for reusing standard components. But should we have that _as well as_ the panels we already have?

**Comment by Mpdreamz** [comment]
+1 on atom-message, in fact looking at typescript atom package

![multiple](https://raw.githubusercontent.com/TypeStrong/atom-typescript-examples/master/screens/findReferences.png)

It has support for multiple outputs using that package, could even replace our complete panel?

We discussed moving to atom-message-panel earlier when we just started this package but back then the message panel did not have this capabilities

**Comment by nosami** [comment]
Ooooh! Didn't realise that was the component atom-typescript used. In that case, yes, we should replace the whole thing.

**Comment by davidfowl** [comment]
Sounds like a plan.

**Comment by willl** [comment]
Looks like a great idea moving over to atom-message-panel. Seems customisable enough to have our own branding etc.

**Comment by sgwill** [comment]
Typescript actually removed `atom-message-panel` in early March. They're relying on `atom-space-pen-views`, just like we are. It does look like they're using it better than we are so we could clean ours up some. But, I don't know that it's worth the work of porting over to atom-message-panel.

**Comment by adriaanp** [comment]
When and how often do we need to do code checks?

I'm confused as to how the server is able to recognize files that have been changes but not saved to disk yet to do the code checks?

The linter is doing something that enables that, because when I disable the linter package, make a code change and not save the file and do a code check, the server does not see that change, but the linter package enabled it does.

Wonder how VSCode is doing it?

**Comment by nosami** [comment]
Changes don't need to be saved to disk for the server to see them. The server has an internal workspace which represents the state of the files as you edit them.

Any update should trigger some action against the server so that the server is always aware of the state of files - so it sounds as if there is a bug there. What type of code change did you make?
