### ISSUE TITLE
Show that packages are being restored.

### ISSUE THREAD

**Issue by adriaanp** [OmniSharp/omnisharp-atom#221]
Would be very helpful to see that packages are being restored without opening the Omnisharp output.

**Comment by AndersNS** [comment]
The built in NotificationManager makes it pretty easy to add this kind of stuff. However since only a filesChanged event is sent to the server the client doesn't know if package restore is finished, failed, or even started correctly. Something on the server would need to give more information if you want warnings or error notifications on package restore failures.

Default behaviour of atom notifications looks like this. 
![restoringpackages](https://cloud.githubusercontent.com/assets/1052521/7512812/d8d56d54-f4af-11e4-84ab-6aec90755ebc.gif)

**Comment by david-driscoll** [comment]
We can listen to the incoming events and look for the package restore finished event.

**Comment by nosami** [comment]
Saw this today ![paket](http://fsprojects.github.io/Paket/img/paket-add-atom.gif)

I'm not sure if it's worth the effort though.

**Comment by AndersNS** [comment]
I looked into this a bit yesterday. The server sends quite a few events back after PackageRestoreStarted that can be used to populate a notification with information a la the gif posted by @nosami above (from atom-packet). 

What I'm thinking currently based on looking at the events the server sends back when doing package restore:
 - The server sends the PackageRestoreStarted event, display the notification.
 - The server sends a list of packages it has detected as missing, append that into the notification
 - The server sends a message each time it installs a package, append that to the notification
 - The server tells us package restore is done, append that to the notification and set it as successful
 - Dismiss the notification 3 seconds after package restore is complete

That way the notification displays what was attempted installed, what was installed and what versions, and success/failure. 

I can toss together a PR by the end of the week if that sounds alright? I'll try to make it easy to create more notifications based on server events in the future.

**Comment by nosami** [comment]
@AndersNS sounds good!

**Comment by sgwill** [comment]
:+1: Fabulous idea

**Comment by nosami** [comment]
fixed in 0.5.0
