### ISSUE TITLE
toggle omnisharp-atom error

### ISSUE THREAD

**Issue by VirtualOverride** [OmniSharp/omnisharp-atom#60]
when toggle to omnisharp-atom i encounter some error, I'm not sure if i need to run the omnisharp server.

starting omnisharp server mono could not be found please ensure it is installed and in you path
![error](https://cloud.githubusercontent.com/assets/6830923/6348667/ddacc48e-bc5c-11e4-98c5-dbf58671a7b9.png)

**Comment by Mpdreamz** [comment]
What operating system are you using? Did you install mono on it?

**Comment by VirtualOverride** [comment]
OS: OS X Yosemite. yup i install mono on this. Mono JIT compiler version 3.12.0. i installed mono using homebrew.

**Comment by stephen-james** [comment]
Theres a problem with process.env.path in atom / apps launched using open rather than from the terminal.  This is detailed in this discussion https://github.com/atom/atom-shell/issues/550

If you launch atom from your terminal, it'll work, because it will have your user path in the process and will hence be able to find mono.

If you launch it from the dock it won't.

We could introduce a requirement to have a seperate environment variable for a mono path as it seems its just the $Path env variable that gets affected this way, but thats also not an ideal solution.

**Comment by VirtualOverride** [comment]
@stephen-james your right its works for me if i launch it via terminal thanks for this. i got this bunch of warnings in omnisharp-atom. do i ignore this? or i miss something to install.

![warning](https://cloud.githubusercontent.com/assets/6830923/6361553/7a8cc9c8-bcbe-11e4-832b-3716b0e8cadf.png)

**Comment by VirtualOverride** [comment]
@stephen-james, @Mpdreamz regarding the error i install mdk via brew cask
"brew cask install mono-mdk" event if you launch it via dock and terminal, the intellisense is work. my bad i though install mono via brew "brew install mono" will install the mdk. i think we can close this. i will create new issue regarding the warnings i got with omnisharp. many thanks to all.

**Comment by usersxm** [comment]
I'm having the same issue.. But in my case didn't work opening atom from terminal.. What can I do?
